### ISSUE TITLE
Un fichier ne doit avoir qu'une seule class

### ISSUE THREAD

**Issue by GauthierPLM** [Nels885/help_MacGyver_escape#1]
Chaque class doit avoir son propre fichier, nommé avec le nom de la class en minuscule.
C'est important pour garder un code lisible et facilement navigable.
Actuellement, comment puis-je savoir que ta classe Objects est dans ton fichier labyrinth.py ?

**Comment by Nels885** [comment]
Ok, je vais créer un fichier pour chaque classe ;)
