### ISSUE TITLE
Utilisation de property

### ISSUE THREAD

**Issue by GauthierPLM** [Nels885/help_MacGyver_escape#3]
https://github.com/Nels885/help_MacGyver_escape/blob/6b9495dbe4bd9f552e29346f9c28e609c65cc957/labyrinth.py#L14

Pourquoi utiliser @property ? Tu n'utilise pas cette fonciton en tant que propriété par la suite.
Property est surtout fait pour des attributs que tu veux utiliser à l'extérieur de ta classe.

**Comment by Nels885** [comment]
j'avais utilisé @property au début pour afficher la structure de mon labyrinthe dans la fonction "main" mais elle ne me sert plus a rien, je vais la retirer.
